name: 🚀 Student Assignment Submission
description: Submit your task tracker enhancement assignment here.
title: "[Assignment Submission] Your Full Name"
labels: [submission, student]
assignees: ''

body:
  - type: input
    id: student-name
    attributes:
      label: 🙋 Full Name
      placeholder: e.g. Gurpinder Sidhu
    validations:
      required: true

  - type: input
    id: github-url
    attributes:
      label: 🔗 GitHub Repo URL
      placeholder: https://github.com/your-username/task-tracker-assignment
    validations:
      required: true

  - type: input
    id: live-demo
    attributes:
      label: 🌐 Live Demo (if deployed)
      placeholder: https://your-app.vercel.app
    validations:
      required: false

  - type: textarea
    id: features
    attributes:
      label: ✨ Features Completed
      description: Briefly describe what features you implemented
      placeholder: "• Added priority filter\n• Integrated subtasks..."
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: 💬 Anything you'd like feedback on?
      placeholder: "Let us know where you'd like suggestions..."
    validations:
      required: false